/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:8cf6c836-0134-48ec-ae15-c491594e3ced",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_xzTIExZKN",
    "aws_user_pools_web_client_id": "5ildjmeul31medsht8kldntvjc",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://fkos6kbbdjfhnkp6a326vz54ie.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
