version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "orders-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ka9fn1pcpxdv"
s3_prefix = "orders-api"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
