version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bhara1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ka9fn1pcpxdv"
s3_prefix = "bhara1"
region = "ca-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
