@baseEndpoint = https://svaqz3hv00.execute-api.us-east-1.amazonaws.com/prod
@email = alex@mls.com
@orderId = db0a9597-78fc-4fb1-bd21-0971d97035c1

### GET All Order
GET {{baseEndpoint}}/orders HTTP/1.1


### GET All Product by Email client
GET {{baseEndpoint}}/orders?email={{email}} HTTP/1.1


### GET 1 Order by Email and order ID
GET {{baseEndpoint}}/orders?email={{email}}&orderId={{orderId}} HTTP/1.1


### POST - Create an Order
POST {{baseEndpoint}}/orders HTTP/1.1
content-type: application/json

# {
#   "email": "hard@code.com",
#   "productIds": ["8e5d9405-712a-4710-b8b1-97a091c1865f", "a05874e6-4ac1-4147-89a6-75cb3cb4eb2e"],
#   "payment": "CASH",
#   "shipping": {
#     "type": "URGENT",
#     "carrier": "UPS"
#   }
# }
{
  "email": "alex@mls.com",
  "productIds": [
    "a05874e6-4ac1-4147-89a6-75cb3cb4eb2e", 
    "8e5d9405-712a-4710-b8b1-97a091c1865f",
    "fcf38ae0-2ca1-44d7-9748-5cab59c37e23"
  ],
  "payment": "DEBIT",
  "shipping": {
    "type": "URGENT",
    "carrier": "UPS"
  }
}

### DELETE - Remove an Order 
DELETE {{baseEndpoint}}/orders?email={{email}}&orderId={{orderId}} HTTP/1.1