@baseEndpoint = https://svaqz3hv00.execute-api.us-east-1.amazonaws.com/prod
@email = alex@mls.com
@orderId = 33de77b9-8344-4b47-8b86-c4d7c295a30e

### GET All Order
GET {{baseEndpoint}}/orders HTTP/1.1


### GET All Product by Email client
GET {{baseEndpoint}}/orders?email={{email}} HTTP/1.1


### GET 1 Order by Email and order ID
GET {{baseEndpoint}}/orders?email={{email}}&orderId={{orderId}} HTTP/1.1


### POST - Create an Order
POST {{baseEndpoint}}/orders HTTP/1.1
content-type: application/json

{
  "email": "john@azure.com",
  "productIds": ["fcf38ae0-2ca1-44d7-9748-5cab59c37e23"],
  "payment": "DEBIT",
  "shipping": {
    "type": "URGENT",
    "carrier": "UPS"
  }
}

### DELETE - Remove an Order 
DELETE {{baseEndpoint}}/orders?email={{email}}&orderId={{orderId}} HTTP/1.1