@baseEndpoint = https://svaqz3hv00.execute-api.us-east-1.amazonaws.com/prod
@productId = a05874e6-4ac1-4147-89a6-75cb3cb4eb2e

### GET All Products
GET {{baseEndpoint}}/products HTTP/1.1


### GET One Product 
GET {{baseEndpoint}}/products/{{productId}} HTTP/1.1


### POST - Create Product
POST {{baseEndpoint}}/products HTTP/1.1
content-type: application/json

{
  "productName": "BasketBall black",
  "productUrl": "ball/300",
  "model": "BasketBall",
  "price": 39.00,
  "code": "400"
}


### PUT - Update Product 
PUT {{baseEndpoint}}/products/{{productId}} HTTP/1.1
content-type: application/json

{
  "productName": "Bycicle",
  "productUrl": "bike/200",
  "model": "Caloi",
  "price": 199.99,
  "code": "200"
}


### DELETE - remove Product 
DELETE {{baseEndpoint}}/products/{{productId}} HTTP/1.1