@baseEndpoint = https://svaqz3hv00.execute-api.us-east-1.amazonaws.com/prod
@productId = 3eae23c6-59aa-4686-bfe0-68f7af8fe1b2

### GET All Products
GET {{baseEndpoint}}/products HTTP/1.1


### GET One Product 
GET {{baseEndpoint}}/products/{{productId}} HTTP/1.1


### POST - Create Product
POST {{baseEndpoint}}/products HTTP/1.1
content-type: application/json

{
  "productName": "Tennis Racket",
  
  "model": "Tennis",
  "price": 70.00,
  "code": "500"
}


### PUT - Update Product 
PUT {{baseEndpoint}}/products/{{productId}} HTTP/1.1
content-type: application/json

{
  "productName": "Bycicle",
  "productUrl": "bike/200",
  "model": "Caloi",
  "price": 199.99,
  "code": "200"
}


### DELETE - remove Product 
DELETE {{baseEndpoint}}/products/{{productId}} HTTP/1.1